### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:  请问你使用的是哪个版本的torch？我用的2.1.0 2.3.1 2.4的都报这个错

### ISSUE THREAD

**Issue by dotsonliu** [sail-sg/regmix#6]
Traceback (most recent call last):
  File "/home/caslx/qwen/conda/envs/liudongze/bin/lightning", line 8, in <module>
    sys.exit(_cli_entry_point())
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/__init__.py", line 47, in _cli_entry_point
    main()
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/app/cli/lightning_cli.py", line 109, in main
    _main()
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/app/utilities/exceptions.py", line 37, in invoke
    return super().invoke(ctx)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/fabric/cli.py", line 129, in _run_model
    main(args=Namespace(**kwargs), script_args=script_args)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/fabric/cli.py", line 187, in main
    _torchrun_launch(args, script_args or [])
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/lightning/fabric/cli.py", line 182, in _torchrun_launch
    torchrun.main(torchrun_args)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/caslx/qwen/conda/envs/liudongze/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by SivilTaram** [comment]
@dotsonliu Hi 你好，我用的是2.1.0。可以尝试在lighting-gpt或者tinyllama的issue里找找是否有相应的解决方案？

**Comment by dotsonliu** [comment]
感谢，已解决，我用的2.3可以跑通 主要是xformers 和 flashattention版本问题

**Comment by SivilTaram** [comment]
@dotsonliu 感谢反馈！这两个库安装起来是有点头疼...
